### ISSUE TITLE
Don't panic when folder doesn't exist

### ISSUE THREAD

**Issue by JakeChampion** [stevenjack/cig#26]
Trialling a new bug report structure - 
## Steps to reproduce:

1 - Add a folder that doesn't exist to your cig settings
2 - Run `cig`
## Expected result:

A user friendly error message mentioning the folder does not exist - _Bonus: Do a fuzzy search to see if it was a misspelling, if it was then mention this in the error_
## Actual result:

```
Checking 'work' (/Users/jakechampion/Projects/work) repos...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x35b6]

goroutine 16 [running]:
runtime.panic(0x1a73a0, 0x2d2864)
    /usr/src/go/src/pkg/runtime/panic.c:279 +0xf5
main.func·001(0x208348420, 0x21, 0x0, 0x0, 0x22083383f0, 0x2083484e0, 0x0, 0x0)
    /go/src/github.com/stevenjack/cig/cig.go:81 +0xc6
path/filepath.Walk(0x208348420, 0x21, 0x208387ae0, 0x0, 0x0)
    /usr/src/go/src/pkg/path/filepath/path.go:388 +0xa9
main.func·002(0x2083820e0)
    /go/src/github.com/stevenjack/cig/cig.go:88 +0x725
github.com/codegangsta/cli.(*App).Run(0x20834a0f0, 0x208326000, 0x1, 0x1, 0x0, 0x0)
    /go/src/github.com/codegangsta/cli/app.go:182 +0xc1e
main.main()
    /go/src/github.com/stevenjack/cig/cig.go:99 +0x1b5

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
    /usr/src/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
    /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
    /usr/src/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
    /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
    /usr/src/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
    /usr/src/go/src/pkg/runtime/proc.c:1445

goroutine 20 [runnable]:
main.output(0x20832a300)
    /go/src/github.com/stevenjack/cig/cig.go:102
created by main.func·002
    /go/src/github.com/stevenjack/cig/cig.go:50 +0xb0
```

**Comment by stevenjack** [comment]
@JakeChampion Like the bug report structure. Certainly need to catch this rather than panicking, thanks for picking it up :+1:
